### ISSUE TITLE
MultiSensor support

### ISSUE THREAD

**Issue by seehase** [heubeck/samler#7]
Please support of more than one sensor
I have two powermeter, 
* PV Generation
* Power pull/push

I want to have values of both (or more) stored in one database/table
Values must be identified by powermeter id, not by USB Port, so if the powermeter sends an identifier take this as a key
Sensor switch (usb port switch) should result in the same results in the DB

**Comment by heubeck** [comment]
Don't see a reason for this.
It would complicate codebase (that makes us of singletons) and also complicate configuration.

One can simply run two instances, writing to different database tables, joined by a view, for a unified access.

Happy to keep this issue, maybe there are other pro arguments.

**Comment by seehase** [comment]
can be closed, a single instance per sensor is working fine
